### PR TITLE
Fix `connect` and `connectTLS` and missing export

### PR DESCRIPTION
**Pull request by cbioley**

### CODE REVIEW

**Comment by cbioley** [comment]
CI failed again, I know ;)

**Comment by thr-eki** [comment]
Hello,

Any plans on merging this branch ? No breaking changes here, on the contrary, the project is unusable as is.

**Comment by sriio** [comment]
@cbioley : You miss to change the `connectTLS` method (we can't use auth with tls despite this PR)

Actual : `  async connectTLS(config: ConnectConfig) { ...`

Needed : `  async connectTLS(config: ConnectConfig | ConnectConfigWithAuthentication) { ...`

**Comment by cbioley** [comment]
@sriio Thanks 👍

**Comment by femave** [comment]
Hope you merge it as soon as posible! GJ

**Comment by pzi** [comment]
Sadly it is un-useable without those types :( Please 🚢  it :)

**Pull request closed without merging**
